# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cell-selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2136, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 200, 1521, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev_marked_frame_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.prev_marked_frame_btn.setMaximumSize(QtCore.QSize(285, 16777215))
        self.prev_marked_frame_btn.setObjectName("prev_marked_frame_btn")
        self.horizontalLayout_2.addWidget(self.prev_marked_frame_btn)
        self.prev_frame_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.prev_frame_btn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.prev_frame_btn.setObjectName("prev_frame_btn")
        self.horizontalLayout_2.addWidget(self.prev_frame_btn)
        self.cur_frame_txt = QtWidgets.QTextEdit(self.layoutWidget)
        self.cur_frame_txt.setMaximumSize(QtCore.QSize(90, 90))
        self.cur_frame_txt.setObjectName("cur_frame_txt")
        self.horizontalLayout_2.addWidget(self.cur_frame_txt)
        self.next_frame_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.next_frame_btn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.next_frame_btn.setObjectName("next_frame_btn")
        self.horizontalLayout_2.addWidget(self.next_frame_btn)
        self.next_marked_frame_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.next_marked_frame_btn.setMaximumSize(QtCore.QSize(285, 16777215))
        self.next_marked_frame_btn.setObjectName("next_marked_frame_btn")
        self.horizontalLayout_2.addWidget(self.next_marked_frame_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(62)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_vessel_mask_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.load_vessel_mask_btn.setObjectName("load_vessel_mask_btn")
        self.horizontalLayout.addWidget(self.load_vessel_mask_btn)
        self.load_cell_positions_csv_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.load_cell_positions_csv_btn.setObjectName("load_cell_positions_csv_btn")
        self.horizontalLayout.addWidget(self.load_cell_positions_csv_btn)
        self.load_mask_video_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.load_mask_video_btn.setObjectName("load_mask_video_btn")
        self.horizontalLayout.addWidget(self.load_mask_video_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.debugDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.debugDisplay.setGeometry(QtCore.QRect(20, 450, 2101, 121))
        self.debugDisplay.setObjectName("debugDisplay")
        self.vessel_mask_loaded_lbl = QtWidgets.QLabel(self.centralwidget)
        self.vessel_mask_loaded_lbl.setGeometry(QtCore.QRect(31, 59, 246, 33))
        self.vessel_mask_loaded_lbl.setObjectName("vessel_mask_loaded_lbl")
        self.filed_loaded_target_lbl = QtWidgets.QLabel(self.centralwidget)
        self.filed_loaded_target_lbl.setGeometry(QtCore.QRect(292, 11, 1821, 33))
        self.filed_loaded_target_lbl.setObjectName("filed_loaded_target_lbl")
        self.vessel_mask_loaded_target_lbl = QtWidgets.QLabel(self.centralwidget)
        self.vessel_mask_loaded_target_lbl.setGeometry(QtCore.QRect(292, 59, 1471, 33))
        self.vessel_mask_loaded_target_lbl.setObjectName("vessel_mask_loaded_target_lbl")
        self.cell_positions_csv_target_lbl = QtWidgets.QLabel(self.centralwidget)
        self.cell_positions_csv_target_lbl.setGeometry(QtCore.QRect(292, 107, 1751, 33))
        self.cell_positions_csv_target_lbl.setObjectName("cell_positions_csv_target_lbl")
        self.mask_video_file_target_lbl = QtWidgets.QLabel(self.centralwidget)
        self.mask_video_file_target_lbl.setGeometry(QtCore.QRect(292, 155, 1791, 33))
        self.mask_video_file_target_lbl.setObjectName("mask_video_file_target_lbl")
        self.mask_video_file_lbl = QtWidgets.QLabel(self.centralwidget)
        self.mask_video_file_lbl.setGeometry(QtCore.QRect(31, 155, 195, 33))
        self.mask_video_file_lbl.setObjectName("mask_video_file_lbl")
        self.file_loaded_lbl = QtWidgets.QLabel(self.centralwidget)
        self.file_loaded_lbl.setGeometry(QtCore.QRect(31, 11, 137, 33))
        self.file_loaded_lbl.setObjectName("file_loaded_lbl")
        self.cell_positions_csv_lbl = QtWidgets.QLabel(self.centralwidget)
        self.cell_positions_csv_lbl.setGeometry(QtCore.QRect(31, 107, 214, 33))
        self.cell_positions_csv_lbl.setObjectName("cell_positions_csv_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2136, 47))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.load_vessel_mask_btn.clicked.connect(self.loadVesselMaskSlot)
        self.load_cell_positions_csv_btn.clicked.connect(self.loadCellPositionsCsvSlot)
        self.load_mask_video_btn.clicked.connect(self.loadMaskVidSlot)
        self.next_frame_btn.clicked.connect(self.goToNextFrameSlot)
        self.prev_frame_btn.clicked.connect(self.goToPrevFrameSlot)
        self.next_marked_frame_btn.clicked.connect(self.goToNextMarkedFrameSlot)
        self.prev_marked_frame_btn.clicked.connect(self.goToPrevMarkedFrameSlot)
        self.actionNew.triggered.connect(self.newVideoSlot)
        self.actionSave.triggered.connect(self.saveSlot)
        self.actionSave_As.triggered.connect(self.saveAsSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prev_marked_frame_btn.setText(_translate("MainWindow", "<< Prev Marked Frame"))
        self.prev_frame_btn.setText(_translate("MainWindow", "< Prev Frame"))
        self.next_frame_btn.setText(_translate("MainWindow", "Next Frame >"))
        self.next_marked_frame_btn.setText(_translate("MainWindow", "Next Marked Frame >>"))
        self.load_vessel_mask_btn.setText(_translate("MainWindow", "Load Vessel Mask"))
        self.load_cell_positions_csv_btn.setText(_translate("MainWindow", "Load Cell Positions Csv"))
        self.load_mask_video_btn.setText(_translate("MainWindow", "Load Mask vid"))
        self.vessel_mask_loaded_lbl.setText(_translate("MainWindow", "Vessel Mask Loaded:"))
        self.filed_loaded_target_lbl.setText(_translate("MainWindow", "-"))
        self.vessel_mask_loaded_target_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.cell_positions_csv_target_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.mask_video_file_target_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.mask_video_file_lbl.setText(_translate("MainWindow", "Mask Video  file:"))
        self.file_loaded_lbl.setText(_translate("MainWindow", "File loaded:"))
        self.cell_positions_csv_lbl.setText(_translate("MainWindow", "Cell Positions Csv:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New Video"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save current selected cell points."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setStatusTip(_translate("MainWindow", "Save file to a new location"))

    @QtCore.pyqtSlot()
    def loadVesselMaskSlot(self):
        pass

    @QtCore.pyqtSlot()
    def loadCellPositionsCsvSlot(self):
        pass

    @QtCore.pyqtSlot()
    def loadMaskVidSlot(self):
        pass

    @QtCore.pyqtSlot()
    def goToNextFrameSlot(self):
        pass

    @QtCore.pyqtSlot()
    def goToPrevFrameSlot(self):
        pass

    @QtCore.pyqtSlot()
    def goToNextMarkedFrameSlot(self):
        pass

    @QtCore.pyqtSlot()
    def goToPrevMarkedFrameSlot(self):
        pass

    @QtCore.pyqtSlot()
    def newVideoSlot(self):
        pass

    @QtCore.pyqtSlot()
    def saveSlot(self):
        pass

    @QtCore.pyqtSlot()
    def saveAsSlot(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
